runs:
  using: composite
  steps:
    - name: free up storage
      shell: bash
      run: |
        sudo swapoff -a
        sudo find /mnt -mindepth 1 -delete
        sudo chmod 1777 /mnt
    - name: install required packages
      shell: bash
      run: |
        sudo apt-get update
        sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends make podman python3 python3-venv uidmap qemu-user-static
    - name: get system info
      shell: bash
      run: |
        exec 2>&1
        set -x
        uname -a
        free -h
        df -h
        bash --version
        git --version
        make --version
        python3 --version
        podman --version
        podman system df -v
