#!/usr/bin/env bash

set -eufo pipefail

arch="$1"
version="$2"
repo="$3"

mkdir /chroot
chmod 755 /chroot
container=lxc debootstrap --keyring /keyring --arch "$arch" --variant minbase "$version" /chroot "$repo" bookworm || (cat /chroot/debootstrap/debootstrap.log; false)

cp /keyring "/chroot/etc/apt/trusted.gpg.d/keyring.gpg"
echo "deb $repo $version main" > /chroot/etc/apt/sources.list

find /chroot/proc /chroot/sys /chroot/dev /chroot/run /chroot/tmp -mindepth 1 -delete
tar --create --sort name --xattrs --xattrs-include 'security.*' --numeric-owner --pax-option=exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime --transform 's|^\./||' --directory /chroot . > /output
