#!/usr/bin/env bash

set -eufo pipefail

IFS=',' read -r -a features <<< "$BUILDER_FEATURES"

mkdir /chroot

# tmpfs is required to allow setting security xattrs in user namespace
mount -t tmpfs tmpfs /chroot

tar --extract --xattrs --xattrs-include '*' --directory /chroot < /input

rm -rf /chroot/builder

mount --rbind /proc /chroot/proc
mount --bind /native_bin /chroot/native_bin

for feature in "${features[@]}"; do
	if [ -e "/builder/features/$feature/exec.post" ]; then
		printf 'exec: %s\n' "/builder/features/$feature/exec.post"
		"/builder/features/$feature/exec.post" /chroot 2>&1 | sed 's/^/  /'
	fi
done

umount /chroot/native_bin
rmdir /chroot/native_bin
umount -l /chroot/proc

tar --create --sort name --xattrs --xattrs-include '*' --transform 's|^\./||' --directory /chroot . > /output
