#!/usr/bin/env bash

set -euo pipefail
shopt -s nullglob

cname="$1"

IFS=',' read -r -a features < <($PYTHON parse_features --feature-dir "$CONFIG_DIR/features" --cname "$cname" features)

artifacts=(".build/$cname.tar")

for feature in "${features[@]}"; do
	for i in "$CONFIG_DIR/features/$feature/"{image,convert}.*; do
		extension="$(grep -E -o '(\.[a-z][a-zA-Z0-9\-_]*)*$' <<< "$i")"
		if [ "$extension" = ".container_archive" ]; then
			extension=".$CONTAINER_ARCHIVE_FORMAT"
		fi
		artifacts+=(".build/$cname$extension")
	done
done

if [ "${#artifacts[@]}" = 0 ] && [ -n "$($PYTHON parse_features --feature-dir "$CONFIG_DIR/features" --cname "$cname" platforms)" ]; then
	artifacts+=(".build/$cname.raw")
fi

echo "${artifacts[@]}"
