name: build
on: push
jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: setup runner
        uses: ./.github/actions/setup
      - name: build
        run: make -j $(nproc) --output-sync TMPDIR=/mnt base-amd64 base-arm64
      - name: list build artifacts
        run: ls -lah .build/
      - name: cache
        uses: actions/cache/save@v3
        with:
          path: .build
          key: base-${{ github.run_id }}-${{ github.run_attempt }}
  build:
    runs-on: ubuntu-latest
    needs: base
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: setup runner
        uses: ./.github/actions/setup
      - name: cache
        uses: actions/cache/restore@v3
        with:
          path: .build
          key: base-${{ github.run_id }}-${{ github.run_attempt }}
      - name: update cache timestamps
        run: |
          t="$(date '+%s')"
          find .build -exec touch -d "@$t" {} +
      - name: build
        run: make -j $(nproc) --output-sync TMPDIR=/mnt
      - name: list build artifacts
        run: ls -lah .build/
      - name: pack build artifacts
        run: tar --create .build | zstd > build.tar.zstd
      - name: upload bulid artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build.tar.zstd
          path: build.tar.zstd
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: setup runner
        uses: ./.github/actions/setup
      - name: build
        run: make -j $(nproc) --output-sync TMPDIR=/mnt CONTAINER_ENGINE=docker base
      - name: list build artifacts
        run: ls -lah .build/
  # build-debian:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v3
  #       with:
  #         submodules: true
  #     - name: setup runner
  #       uses: ./.github/actions/setup
  #     - name: build
  #       run: make -j $(nproc) --output-sync TMPDIR=/mnt REPO=http://deb.debian.org/debian base
  #     - name: list build artifacts
  #       run: ls -lah .build/
